services:
    cash:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/usr/local/cash
        ports:
            - '5260:5260'
            - '7053:7053'
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            MongoDB__Host: mongodb
            MongoDB__Port: 27017
            MongoDB__Username: ${MONGODB_USERNAME}
            MongoDB__Password: ${MONGODB_PASSWORD}
            MongoDB__Database: ${MONGODB_DATABASE}
        depends_on:
            - mongodb

    mongodb:
        image: mongo:8.0.9
        volumes:
            - mongodb-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}

volumes:
    mongodb-data:
